language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION="1.4"
  - DJANGO_VERSION="1.5"
  - DJANGO_VERSION="1.6"
  - DJANGO_VERSION="1.7"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION="1.4"
    - python: "3.4"
      env: DJANGO_VERSION="1.4"
install:
  - pip install -r requirements.txt
  - pip install "Django>1.4,<$DJANGO_VERSION.99"
  - pip install coveralls
script:
  - make test doc quality
after_success:
  - coveralls
