name: Upgrade Python Requirements

on:
  schedule:
    # will start the job at 01:30 UTC every Friday
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch against which to create requirements PR"
        required: true
        default: 'master'

jobs:
  call-upgrade-python-requirements-workflow:
    uses: openedx/.github/.github/workflows/upgrade-python-requirements.yml@master
    with:
      branch: ${{ github.event.inputs.branch || 'master' }}
      # optional parameters below; fill in if you'd like github or email notifications
      # user_reviewers: ""
      team_reviewers: "axim-engineering"
      # email_address: ""
      # send_success_notification: false
    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
  
  tag-axim-team-for-review:     
    name: Tag Axim Team for review
    runs-on: ubuntu-latest
    steps:
      - name: Mention aximprovements team
        uses: actions/github-script@v4         
        with:           
          script: |
              const teamName = "openedx/axim-aximprovements";
              const prNumber = context.payload.pull_request.number;
              const comment = `@${teamName} New pull request (#${prNumber})for review
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: comment
              });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

