name: Upgrade Python Requirements

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch against which to create requirements PR"
        required: true
        default: 'master'

jobs:
  call-upgrade-python-requirements-workflow:
    uses: openedx/.github/.github/workflows/upgrade-python-requirements.yml@kdmccormick/testeng-ci-to-repo-tools
    # Do not run on forks
    if: github.repository_owner == 'openedx'
    with:
      branch: ${{ github.event.inputs.branch || 'master' }}
      # optional parameters below; fill in if you'd like github or email notifications
      user_reviewers: "kdmccormick"
      email_address: "kyle@axim.org"
      send_success_notification: false
    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
